from __future__ import annotations


MATERIAL_RETURN = "Material Return"
MATERIAL_SCRAP = "Material Scrap"
PROCESS_LOSS = "Process Loss"

REQUEST_TYPES = {MATERIAL_RETURN, MATERIAL_SCRAP, PROCESS_LOSS}
MATERIAL_REQUEST_TYPES = {MATERIAL_RETURN, MATERIAL_SCRAP}
CAUSES = {"Material Defect", "Operation Error", "Other"}

PENDING_APPROVAL = "Pending Approval"
APPROVED = "Approved"
AWAITING_STOCK_ENTRY = "Awaiting Stock Entry"
APPLIED = "Applied"
COMPLETED = "Completed"
REJECTED = "Rejected"
WITHDRAWN = "Withdrawn"
CONTINUE_PRODUCTION = "Continue"
RELEASE_ASSIGNMENT = "Release"

REQUEST_STATUSES = {
	PENDING_APPROVAL,
	APPROVED,
	AWAITING_STOCK_ENTRY,
	APPLIED,
	COMPLETED,
	REJECTED,
	WITHDRAWN,
}

OPEN_MATERIAL_STATUSES = {PENDING_APPROVAL, APPROVED, AWAITING_STOCK_ENTRY}
